name: Gradle Build

on:
  push:
    branches:
      - main  # Build the project on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Specifies that the job should run on a self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Action to checkout the repository's code

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'  # Use OpenJDK 8

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build --no-daemon  # Command to build the project




# on:
#   # Trigger analysis when pushing in master or pull requests, and when creating
#   # a pull request. 
#   push:
#     branches:
#       '*'
#   pull_request:
#       types: [opened, synchronize, reopened]

# name: SonarQube Scan
# jobs:
#   sonarqube:
#     name: SonarQube Trigger
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checking out
#       uses: actions/checkout@master
#       with:
#         # Disabling shallow clone is recommended for improving relevancy of reporting
#         fetch-depth: 0
#     - name: SonarQube Scan
#       uses: kitabisa/sonarqube-action@v1.2.0
#       with:
#         host: https://db36-158-228-253-36.ngrok-free.app 
#         login: f85d7b3fd32ecc3582848d6644cd5b986d562086 
#         projectKey: check
