name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          sonar-url: ${{ secrets.SONAR_HOST_URL }} # URL of your SonarQube server
          sonar-login: ${{ secrets.SONAR_TOKEN }} # Authentication token
          project-key: check # Project key in SonarQube
