name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          sonar-url: ${{ secrets.SONAR_HOST_URL }} # URL of your SonarQube server
          sonar-login: ${{ secrets.SONAR_TOKEN }} # Authentication token
          project-key: check # Project key in SonarQube
